---
- name: Tensorflow Object Detection API
  hosts: cybera
  become_method: sudo
  become_user: root

  tasks:
    - name: Install pip2
      become: yes
      apt:
        name: python-pip
        update_cache: yes

    - name: Install python-tk
      become: yes
      apt:
        name: python-tk
        update_cache: yes

    - name: Check protobuf-3 exists in mounted volume
      stat:
        path: /mnt/data/protoc-3.2.0-linux-x86_64.zip
      register: stat_result
  
    - fail:
        msg: "Protobuf 3 zip file missing"
      when: stat_result.stat.exists == False

    - name: Move protobuf 3 files
      become: yes
      shell: cp -r /mnt/data/protoc3/bin/* /usr/local/bin

    - name: Move protobuf 3 include files
      become: yes
      shell: cp -r /mnt/data/protoc3/include/* /usr/local/include

    - name: pip install TF object detection requirements
      become: yes
      pip:
        name: Cython, contextlib2, lxml, numpy

    - name: Clone Tensorflow/models
      git:
        repo: 'https://github.com/tensorflow/models.git'
        dest: /home/ubuntu/tf_models
        clone: yes
        update: yes

    - name: Clone cocoapi
      git:
        repo: 'https://github.com/waleedka/coco'
        dest: /home/ubuntu/cocoapi
        clone: yes
        update: yes

    - name: Build Coco api
      make:
        chdir: /home/ubuntu/cocoapi/PythonAPI

    - name: Make install Coco api
      become: yes
      make:
        chdir: /home/ubuntu/cocoapi/PythonAPI
        target: install

    - name: Python setup install COCO
      command: chdir=/home/ubuntu/cocoapi/PythonAPI /home/ubuntu/prolixor/venv/bin/python setup.py install

    #- name: Copy pycocotools to tf_models/research
      #command: chdir=/home/ubuntu/cocoapi/PythonAPI cp -r pycocotools /home/ubuntu/tf_models/research

    - name: Protobuf Compilation
      become: yes
      shell: chdir=/home/ubuntu/tf_models/research protoc object_detection/protos/*.proto --python_out=.

    - name: update profile
      lineinfile:
        dest: /home/ubuntu/prolixor/venv/bin/activate
        state: present
        line: 'PYTHONPATH="$HOME/tf_models/research:$HOME/tf_models/research/slim"'

    - name: TF object-detection install pip requirements
      command: chdir=/home/ubuntu/tf_models/research /home/ubuntu/prolixor/venv/bin/pip install .

    - name: TF slim install pip requirements
      command: chdir=/home/ubuntu/tf_models/research/slim /home/ubuntu/prolixor/venv/bin/pip install .

    - name: Create data directory
      file: path=/home/ubuntu/tf_models/research/data state=directory

    - name: Create train directory
      file: path=/home/ubuntu/tf_models/research/train state=directory

    - name: Create eval directory
      file: path=/home/ubuntu/tf_models/research/eval state=directory

    - name: Create models directory
      file: path=/home/ubuntu/tf_models/research/models state=directory

    - name: Create model directory
      file: path=/home/ubuntu/tf_models/research/models/model state=directory

    - name: Copy labels_map.pbtxt to tf_models/research/data
      command: chdir=/home/ubuntu/prolixor cp label_map.pbtxt /home/ubuntu/tf_models/research/data

    - name: Copy train.record to tf_models/research/data
      command: chdir=/mnt/data cp train.record /home/ubuntu/tf_models/research/data

    - name: Copy test.record to tf_models/research/data
      command: chdir=/mnt/data cp test.record /home/ubuntu/tf_models/research/data

    - name: Copy ssd_mobilenet_v2_coco to tf_models/research/models/model
      command: chdir=/mnt/data cp -avr ssd_mobilenet_v2_coco_2018_03_29 /home/ubuntu/tf_models/research/models

    - name: Rename ssd_mobilenet_v2_coco to model
      command: mv /home/ubuntu/tf_models/research/models/ssd_mobilenet_v2_coco_2018_03_29 /home/ubuntu/tf_models/research/models/model

    - name: Copy ssdlite_mobilenet_v2_coco.config to tf_models/research/models/model
      command: chdir=/home/ubuntu/prolixor cp ssdlite_mobilenet_v2_coco.config /home/ubuntu/tf_models/research/models/model
